name = "image-queue-worker"
main = "src/queue-worker.ts"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]

# AI binding
[ai]
binding = "AI"

# R2 Buckets
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "mybonzo-media"
preview_bucket_name = "mybonzo-media-preview"

# KV Namespaces  
[[kv_namespaces]]
binding = "CACHE"
id = "cce469bb54d142ebbbce4287e450daec"
preview_id = "139be3a08d7940eea1de297b0ac22e59"

# Queue Consumer
[[queues.consumers]]
queue = "image-generation-queue"
max_batch_size = 1
max_batch_timeout = 30