name = "mybonzoaiblog"
compatibility_date = "2024-10-28"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces - only existing ones
kv_namespaces = [
  { binding = "SESSION", id = "77d84c01758a4064be011acc35b2c344", preview_id = "183215eb52fa4ef8a7fc312a76e6b688" },
  { binding = "CACHE", id = "cce469bb54d142ebbbce4287e450daec", preview_id = "139be3a08d7940eea1de297b0ac22e59" }
]

# AI binding
ai = { binding = "AI" }

# Durable Objects - disabled for now (complex setup required)
# [durable_objects]
# bindings = [
#   { name = "CHAT_ROOM", class_name = "ChatRoom" }
# ]

# [[migrations]]
# tag = "v1"
# new_classes = ["ChatRoom"]

# Environment variables removed - will be set by CI/CD