name: Keep Site Alive

on:
    schedule:
        # Uruchamia co 10 minut w godzinach aktywności (6:00-22:00 UTC)
        - cron: "*/10 6-22 * * *"
        # Uruchamia co 30 minut w nocy (22:00-6:00 UTC)
        - cron: "*/30 22-23,0-5 * * *"
    workflow_dispatch: # Pozwala na ręczne uruchomienie

jobs:
    keep-alive:
        runs-on: ubuntu-latest

        steps:
            - name: Keep MyBonzo AI Blog Alive
              run: |
                  echo "Pinging MyBonzo AI Blog to keep it alive..."

                  # Lista URL-i do pingowania
                  urls=(
                    "https://mybonzoaiblog.pages.dev"
                    "https://www.mybonzoaiblog.com"
                    "https://mybonzoaiblog.com"
                  )

                  for url in "${urls[@]}"; do
                    echo "Pinging: $url"
                    response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 "$url" || echo "000")
                    
                    if [ "$response" -ge 200 ] && [ "$response" -lt 400 ]; then
                      echo "✅ $url responded with status: $response"
                    else
                      echo "⚠️ $url responded with status: $response"
                    fi
                    
                    # Krótka pauza między requestami
                    sleep 2
                  done

                  echo "Keep-alive ping completed at $(date)"

            - name: Ping API Endpoints
              run: |
                  echo "Pinging API endpoints..."

                  # Jeśli masz API endpoints, dodaj je tutaj
                  api_urls=(
                    "https://mybonzoaiblog.pages.dev/api/health"
                    "https://mybonzoaiblog.pages.dev/api/status"
                  )

                  for url in "${api_urls[@]}"; do
                    echo "Pinging API: $url"
                    response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$url" || echo "000")
                    echo "API $url status: $response"
                    sleep 1
                  done

            - name: Generate Activity
              run: |
                  echo "Generating some activity..."

                  # Symuluj różne typy requestów
                  main_url="https://mybonzoaiblog.pages.dev"

                  # Strona główna
                  curl -s -o /dev/null "$main_url/" || true
                  sleep 1

                  # Różne sekcje (jeśli istnieją)
                  paths=("/blog" "/about" "/contact" "/portfolio")

                  for path in "${paths[@]}"; do
                    echo "Checking: $main_url$path"
                    curl -s -o /dev/null --max-time 10 "$main_url$path" || true
                    sleep 1
                  done

            - name: Log Results
              run: |
                  echo "Keep-alive job completed successfully!"
                  echo "Timestamp: $(date)"
                  echo "All configured URLs have been pinged."
