name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - mybonzo_zoo # Current working branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: List dist directory
        run: ls -la ./dist

      - name: Deploy to Cloudflare Pages (Alternative)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "⚠️ CLOUDFLARE_API_TOKEN not set - skipping deploy"
            echo "Please add CLOUDFLARE_API_TOKEN to GitHub Secrets"
            echo "Built files are ready in ./dist directory"
            exit 0
          fi
          npx wrangler pages deploy ./dist --project-name=my-bonzo-ai-blog --compatibility-date=2024-10-26
