name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: List dist directory
        run: ls -la ./dist

      - name: Debug Environment Variables
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "🔍 DEBUG: Sprawdzanie zmiennych środowiskowych"
          echo "1. Sprawdzanie czy CLOUDFLARE_API_TOKEN istnieje:"
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "❌ CLOUDFLARE_API_TOKEN jest puste"
          else
            echo "✅ CLOUDFLARE_API_TOKEN istnieje (długość: ${#CLOUDFLARE_API_TOKEN} znaków)"
            echo "   Pierwsze 8 znaków: ${CLOUDFLARE_API_TOKEN:0:8}..."
          fi

          echo "2. Sprawdzanie czy CLOUDFLARE_ACCOUNT_ID istnieje:"
          if [ -z "$CLOUDFLARE_ACCOUNT_ID" ]; then
            echo "❌ CLOUDFLARE_ACCOUNT_ID jest puste"
          else
            echo "✅ CLOUDFLARE_ACCOUNT_ID istnieje: $CLOUDFLARE_ACCOUNT_ID"
          fi

          echo "3. Sprawdzanie wszystkich zmiennych środowiskowych z 'CLOUDFLARE':"
          env | grep CLOUDFLARE || echo "Brak zmiennych CLOUDFLARE w środowisku"

          echo "4. Sprawdzanie wersji wrangler:"
          npx wrangler --version

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "⚠️ Missing GitHub Secrets - Add these to your repo:"
            echo "1. CLOUDFLARE_API_TOKEN - your Cloudflare API token"
            echo "2. CLOUDFLARE_ACCOUNT_ID - your Cloudflare account ID"
            echo "Built files are ready in ./dist directory"
            echo "Configure custom domain: www.mybonzoaiblog.com"
            exit 1
          fi

          echo "🔧 Deploying to Cloudflare Pages..."
          echo "Deploying to project: mybonzoaiblog"
          echo "Custom domain will be: www.mybonzoaiblog.com"

          # Sprawdź czy token ma prawidłowy format
          if [[ "$CLOUDFLARE_API_TOKEN" == *" "* ]] || [[ "$CLOUDFLARE_API_TOKEN" == *$'\n'* ]]; then
            echo "⚠️ Token zawiera spacje lub znaki nowej linii - to może być problem"
          fi

          # Usuń potencjalne białe znaki z tokena
          export CLOUDFLARE_API_TOKEN=$(echo "$CLOUDFLARE_API_TOKEN" | tr -d '[:space:]')
          export CLOUDFLARE_ACCOUNT_ID=$(echo "$CLOUDFLARE_ACCOUNT_ID" | tr -d '[:space:]')

          echo "Token po oczyszczeniu (długość: ${#CLOUDFLARE_API_TOKEN})"

          npx wrangler pages deploy ./dist
