name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: List dist directory
        run: ls -la ./dist

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "⚠️ Missing GitHub Secrets - Add these to your repo:"
            echo "1. CLOUDFLARE_API_TOKEN - your Cloudflare API token"
            echo "2. CLOUDFLARE_ACCOUNT_ID - 7f490d58a478c6baccb0ae01ea1d87c3"
            echo "📁 Built files are ready in ./dist directory"
            echo "🚀 To deploy manually run:"
            echo "   npm run build && npx wrangler pages deploy ./dist --project-name=mybonzoaiblog"
            exit 1
          fi

          echo "🔧 Deploying to Cloudflare Pages..."
          echo "Project: mybonzoaiblog"
          echo "Account ID: $CLOUDFLARE_ACCOUNT_ID"
          echo "🌐 Target domains:"
          echo "   • https://mybonzoaiblog.pages.dev"
          echo "   • https://www.mybonzoaiblog.com"

          echo "🚀 Running deployment..."
          npx wrangler pages deploy ./dist --project-name=mybonzoaiblog

          deployment_status=$?
          if [ $deployment_status -eq 0 ]; then
            echo ""
            echo "✅ Deployment complete!"
            echo "🌐 Live URLs:"
            echo "   • https://mybonzoaiblog.pages.dev"
            echo "   • https://www.mybonzoaiblog.com"
          else
            echo ""
            echo "❌ Deployment failed with status: $deployment_status"
            echo "📋 Check the wrangler logs above for error details"
            exit 1
          fi
